---
title: "Isaac21694"
---

In Making Democracy Work, @putnam1993making attempt to explain the regional differences in institutional performance between the North and South of Italy using the proxy of civic community. @putnam1993making find that while socio-economic modernity, advanced by industrialization and economic development, can explain the high performance of Northern Italy, it cannot fully explain the regional differences in institutional performance across the country. Consequently, @putnam1993making deduce that civic community is a more powerful force driving effective governance. We know from @putnam1993making that the civic community conveys ideals of cooperation and solidarity, allowing for increased opportunities for collective action. We also know that the civic community is linked to political leaders being more egalitarian and less focused on hierarchical authority and clientilism. A non-civic community, fostering clientelism and hierarchical authority, might be more prone to corruption and the erosion of democratic institutions as leaders are more focused on transnational politics. Therefore we expect that as the civic community strengthens, a country is more likely to be categorized as a democracy. We can see this relationship in the vdem dataset referring to Figure 1 and Figure 2 . It is important to highlight that the y-axis in Figure 1 is the electoral democracy index. I find that electoral democracy is more practical in this context of analysis as this index focuses on core democratic principles like free and fair elections, voting rights, independent media, freedom of expression, and freedom of association, among others.